// plugins/renamer/src/components/tabs.svelte
<script lang="ts">
interface TabItem {
    label: string
    active: () => boolean
    select: () => void
}

interface Props {
    items: TabItem[]
}

let { items }: Props = $props()
</script>

<div class="tabs">
  {#each items as item}
    <button class="tab" class:active={item.active()} onclick={item.select}>
      {item.label}
    </button>
  {/each}
</div>

<style>
  .tabs {
    display: flex;
    align-items: center;
    height: 52px;
    flex-shrink: 0;
    border-top: 1px solid var(--framer-color-divider);
    border-bottom: 1px solid var(--framer-color-divider);
  }

  .tab {
    background: none;
    border: 0;
    width: auto;
    padding: 0;
    color: #999999;
    font-weight: 600;
    user-select: none;
    padding: 0 5px;
    transition: color 200ms ease;
  }

  .tab:first-child {
    padding-left: 0;
  }

  .tab:active {
    background: none;
  }

  .tab.active {
    color: var(--framer-color-text);
  }
</style>

// plugins/renamer/src/components/Tabs.tsx
import cx from "classnames"

interface TabItem {
    label: string
    active: boolean
    select: () => void
}

interface Props {
    items: TabItem[]
}

export default function Tabs({ items }: Props) {
    const activeIndex = items.findIndex(item => item.active)

    return (
        <div className="tabs">
            <div className="tabs-container">
                <div className="tab-bg-container">
                    {activeIndex !== -1 && (
                        <div
                            className="tab-bg"
                            style={{
                                width: `${100 / items.length}%`,
                                left: `${(100 / items.length) * activeIndex}%`,
                            }}
                        />
                    )}
                </div>

                {items.map((item, index) => (
                    <button key={index} className={cx("tab", item.active && "active")} onClick={item.select}>
                        {item.label}
                    </button>
                ))}
            </div>
        </div>
    )
}
