// plugins/renamer/src/components/TextField.tsx
import { useEffect, useRef } from "react"

interface Props {
    value: string
    setValue: (value: string) => void
    placeholder: string
    focused?: boolean
    disabled?: boolean
    leadingContent?: React.ReactNode
    onKeyDown: (event: React.KeyboardEvent) => void
}

export default function TextField({
    value,
    setValue,
    placeholder,
    focused,
    disabled = false,
    leadingContent,
    onKeyDown,
}: Props) {
    const inputRef = useRef<HTMLInputElement>(null)

    const focusInput = () => {
        inputRef.current?.focus()
    }

    useEffect(() => {
        if (focused) {
            inputRef.current?.focus()
        }
    }, [focused])

    return (
        <div className="text-field" onClick={focusInput} onKeyDown={focusInput} role="textbox" tabIndex={-1}>
            {leadingContent && <div className="leading-content">{leadingContent}</div>}

            <input
                type="text"
                placeholder={placeholder}
                value={value}
                onChange={e => {
                    setValue(e.target.value)
                }}
                ref={inputRef}
                disabled={disabled}
                onKeyDown={onKeyDown}
            />
        </div>
    )
}

// plugins/renamer/src/components/text_field.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    value: string;
    placeholder: string;
    focused?: boolean;
    disabled?: boolean;
    leadingContent?: Snippet;
    onkeydown: (event: KeyboardEvent) => void;
  }

  let { value = $bindable(), placeholder, focused, disabled = false, leadingContent, onkeydown }: Props = $props();

  let inputElement: HTMLInputElement;

  const focusInput = () => {
    inputElement.focus();
  };

  $effect(() => {
    if (focused) {
      inputElement.focus();
    }
  });
</script>

<div class="text-field" onclick={focusInput} onkeydown={focusInput} role="textbox" tabindex="-1">
  {#if leadingContent}
    <div class="leading-content">
      {@render leadingContent?.()}
    </div>
  {/if}

  <input type="text" {placeholder} bind:value bind:this={inputElement} {disabled} {onkeydown} />
</div>

<style>
  .text-field {
    background-color: var(--framer-color-bg-tertiary);
    border-radius: 8px;
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 0 10px;
    height: 30px;
    position: relative;
    overflow: hidden;
  }

  .text-field:focus-within {
    box-shadow: 0 0 0 1px var(--framer-color-tint) inset;
  }

  .leading-content {
    color: var(--framer-color-text-tertiary);
    flex-shrink: 0;
    pointer-events: none;
  }

  input {
    background-color: transparent;
    width: 100%;
    height: 100%;
    padding: 0;
    flex-shrink: 1;
  }

  input:focus {
    box-shadow: none;
  }

  input::placeholder {
    color: #999999;
  }
</style>
